### ISSUE TITLE
Generated tree are repeated after numTrees/2

### ISSUE THREAD

**Issue by hazem-suliman** [titicaca/spark-iforest#9] opened 2019-04-09 21:07 UTC
Tested using the data 
[1.0, 20.0, 200.5, 0.002
2.3, 50.0, 300.75, 0.009
1.3, 20.4, 100.9, 0.0045
10.3, 200.4, 1000.9, 10.45] 

and the command 
IForest iForest = new IForest().setNumTrees(4)
.setContamination(0.3)
.setBootstrap(false)
.setMaxDepth(2)
.setSeed(123456L);

resulting in the following trees:
tree[0]
	featureIndex: 1
	featureValue: 119.1657
	
	-leftChild
		featureIndex: 1
		featureValue: 40.0932
		
tree[1]
	featureIndex: 0
	featureValue: 2.48332
	
	-leftChild
		featureIndex: 0
		featureValue: 2.1810
		
tree[2]
	featureIndex: 1
	featureValue: 119.1657
	
	-leftChild
		featureIndex: 1
		featureValue: 40.0932
		
tree[3]
	featureIndex: 0
	featureValue: 2.48332
	
	-leftChild
		featureIndex: 0
		featureValue: 2.18104

So tree[2] and tree[3] are identical copies of tree[0] and tree[1]. Worth menioning that increasing the number of trees results in similar behavior but later, i.e. if numTrees=10 then the trees will repeat after 5.

I thought it had to do with the seed but while debugging I found that trees [2,3] are not generated anew at all, at some point they seem to be copied from the first ones.

**Comment by titicaca** [comment] 2019-04-10 03:24
Thanks for reporting the problem. It was caused by the random seed during generating iTree. Fixes have been committed.

**Closed as completed by titicaca** 2019-04-10 03:24 UTC
